### ISSUE TITLE
Remapping html reports

### ISSUE THREAD

**Issue by drakson** [SitePen/remap-istanbul#1]
Hi, 

Great module! I'm getting the following exception when reports is configured to 'html'.

```
/project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:203
                endCol = structuredText[startLine].text.originalLength();
                                                  ^
TypeError: Cannot read property 'text' of undefined
    at /project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:203:51
    at Array.forEach (native)
    at annotateStatements (/project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:188:33)
    at HtmlReport.Report.mix.writeDetailPage (/project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:423:9)
    at /project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:484:26
    at SyncFileWriter.extend.writeFile (/project/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/project/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:483:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/project/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:477:23)
```

Btw, the library is not on npm yet :(

Thank you!

**Comment by kitsonk** [comment]
Hmmm... that is interesting.  I suspect something has gone awry in what is being submitted to the report writer.  Do you get any issues when setting the report to "json"?  And if not, would you mind providing that output?

Apologies for lack of npm.  Should be shorted in the next day or so.

**Comment by drakson** [comment]
It only occurs when setting the report to "html". I can't post the json file for privacy reason, but I can tell you is a map generated by transpiling ES6 through babel and it contains the sources embedded in "sourcesContent". When I manually fix the exception by checking the object variable on the if above, it works fine.

Thanks to you for your time :)

**Comment by kitsonk** [comment]
Ok, if other reports write fine, I suspect this is an issue with Istanbul and taking a quick look, it does appear others have run into exactly the same issue: gotwarlost/istanbul#429

I am not sure exactly under what conditions it occurs, but I am going to mark this ticket external.

**Comment by dylans** [comment]
It seems unlikely that the current Istanbul is ever going to resolve this, but the PR at https://github.com/gotwarlost/istanbul/pull/603 likely solves this issue.

Eventually the rewrite of Istanbul will be stable and it supports remapping capabilities based on our work in this project.

**Comment by martinoppitz** [comment]
https://github.com/marcules/karma-remap-istanbul/issues/5
