### ISSUE TITLE
Release 0.8.2 not reverse compatible with 0.8.0

### ISSUE THREAD

**Issue by sebastianovide** [SitePen/remap-istanbul#112]
require('remap-istanbul/lib/gulpRemapIstanbul') became require('remap-istanbul/lib/gulpRemapIstanbul').default and therefore it broke the build.

Should it be 0.9 instead ?

**Comment by atao60** [comment]
karma-remap-coverage is also broken:

:ERROR [coverage]: [TypeError: remap is not a function]
TypeError: remap is not a function
    at null.onCoverageComplete.Object.keys.forEach.reportType [as onCoverageComplete] ([...]/angular2-webpack-starter2/node_modules/karma-remap-coverage/remap-coverage.js:23:23)
    at null.<anonymous> ([...]/angular2-webpack-starter2/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:87:13)
    at null.emit (events.js:172:7)
    at InMemoryReport.writeReport ([...]/angular2-webpack-starter2/node_modules/karma-coverage/lib/in-memory-report.js:14:22)
    at writeReport ([...]/angular2-webpack-starter2/node_modules/karma-coverage/lib/reporter.js:68:16)
    at [...]/angular2-webpack-starter2/node_modules/karma-coverage/lib/reporter.js:290:11
    at Array.forEach (native)
    at null.forEach ([...]/angular2-webpack-starter2/node_modules/karma/lib/browser_collection.js:93:21)
    at [...]/angular2-webpack-starter2/node_modules/karma-coverage/lib/reporter.js:247:16
    at Array.forEach (native)
    at null.onRunComplete ([...]/angular2-webpack-starter2/node_modules/karma-coverage/lib/reporter.js:246:15)
    at null.<anonymous> ([...]/angular2-webpack-starter2/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:92:20)
    at null.emit (events.js:172:7)

Everything runs fine again as soon as version 0.8.0 of remap-istanbul is forced.

**Comment by dylans** [comment]
So the issue we have is 0.8.0 fixed a number of things, and regressed for a number of other users. 0.8.1 and 0.8.2 attempted to fix that and have now regressed things for people where 0.8.0 was working fine. Apologies, we're working to fix asap.

**Comment by jdonaghue** [comment]
@sebastianovide and @atao60 could you both take a look at PR #114 and see if that fixes your issues. I have removed the `api` changes and `default` is no longer required. Thanks!

**Comment by sebastianovide** [comment]
My issue was simply resolved adding **.default** : `require('remap-istanbul/lib/gulpRemapIstanbul').default` That would be fine for 0.9, but a minor version should always be back compatible...

**Comment by jdonaghue** [comment]
@sebastianovide and @atao60 this has been addressed in release `0.8.3`. `.default` is no longer exported. Additionally, `loadCoverage`, `remap` and `writeReport` are all exported when requiring the base module (`require('remap-istanbul')`) again as well.

**Comment by atao60** [comment]
@jdonaghue OK with 0.8.3

**Comment by dylans** [comment]
This mistake should have been resolved with 0.8.3 and 0.8.4. We'll strive to not break semver in the future.
