### ISSUE TITLE
Error if sourceMap has no file attribute

### ISSUE THREAD

**Issue by cexbrayat** [SitePen/remap-istanbul#168]
On one of our projects, bumping from Webpack 3.4.1 to 4.6.0 leads to:

```
03 05 2018 18:29:07.030:ERROR [coverage]: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:1456:5)
    at CoverageTransformer.addFileCoverage (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/remap-istanbul/src/CoverageTransformer.js:144:5)
    at /Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/remap-istanbul/src/CoverageTransformer.js:235:3
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/remap-istanbul/src/CoverageTransformer.js:237:11)
    at /Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/remap-istanbul/src/remap.js:34:7
    at Array.forEach (<anonymous>)
    at remap (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/remap-istanbul/src/remap.js:33:11)
    at RemapCoverageReporter.onCoverageComplete (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-remap-coverage/remap-coverage.js:23:23)
    at Server.<anonymous> (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at InMemoryReport.writeReport (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-coverage/lib/in-memory-report.js:14:22)
    at writeReport (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-coverage/lib/reporter.js:68:16)
    at /Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-coverage/lib/reporter.js:290:11
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma/lib/browser_collection.js:93:21)
    at /Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-coverage/lib/reporter.js:247:16
    at Array.forEach (<anonymous>)
    at CoverageReporter.onRunComplete (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma-coverage/lib/reporter.js:246:15)
    at Server.<anonymous> (/Users/cedric/Code/ninjasquad/ebooks/Angular/tests/node_modules/karma/lib/events.js:13:22)
```

By debugging `CoverageTransformer`, it looks like it expects the `file` attribute of `rawSourceMap` to be defined, and that used to the case in our project with Webpack 3 but not with Webpack 4.6 using `inline-source-map`. See https://github.com/SitePen/remap-istanbul/blob/1b240d346cb609a9514dd0c8fdab0e93176e0867/src/CoverageTransformer.js#L143

SourceMap v3 says that the `file` attribute is optional. Replacing `rawSourceMap.file` by `rawSourceMap.sources[0]` just as a test fixes the issue, but that maybe not the clean way to fix it.

**Comment by dylans** [comment]
This sounds very similar to #167 which was closed because it was fixed in vue-loader. 

I'm thinking maybe this would be ok:

```
origFileName = rawSourceMap.file || rawSourceMap.sources[0];
```

@cexbrayat care to test that change and then raise a PR and then I'll test and land it?

**Comment by cexbrayat** [comment]
@dylans Do you think we can have a release including this fix? Or did I miss it?
