### ISSUE TITLE
Error with multiple sourceMappingURL directives

### ISSUE THREAD

**Issue by frapontillo** [SitePen/remap-istanbul#20]
When compiling typescript files and bundling everything with webpack there may be cases of generated files with multiple `sourceMappingURL` directives (see https://github.com/s-panferov/awesome-typescript-loader/issues/60 and https://github.com/webpack/webpack/issues/273).

This leads to non existing source maps files being loaded by remap-istanbul and causing an error:
```
/my/path/project/node_modules/remap-istanbul/lib/remap.js:133
				throw new Error('Could not find file: "' + filePath + '"');
				^

Error: Could not find file: "/my/path/project/.tmp/index.module.js.map"
    at readJSON (/my/path/project/node_modules/remap-istanbul/lib/remap.js:133:11)
    at /my/path/project/node_modules/remap-istanbul/lib/remap.js:172:21
    at Array.forEach (native)
    at /my/path/project/node_modules/remap-istanbul/lib/remap.js:153:22
    at Array.forEach (native)
    at remap (/my/path/project/node_modules/remap-istanbul/lib/remap.js:152:12)
    at DestroyableTransform._transform (/my/path/project/node_modules/remap-istanbul/lib/gulpRemapIstanbul.js:31:20)
    at DestroyableTransform.Transform._read (/my/path/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/my/path/project/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/my/path/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/my/path/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/my/path/project/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/my/path/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/my/path/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/my/path/project/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)

```

The error is due to how you select the source map directive at https://github.com/SitePen/remap-istanbul/blob/master/lib%2Fremap.js#L169, trusting that there is only one of those.
Is there a way we can change or customise the match selection through proper options? I think this might be straightforward and could easily be implemented in a PR, if you agree with the purpose of the change.

Thanks.

**Comment by kitsonk** [comment]
Implementing an option to override the source map directive matcher would be fine and I can take a look at it if no one wants to do a PR.  I think there is a bigger challenge, because `remap-istanbul` only expects a single source-map file, which of course can contain multiple source files.  The specification allows such things as well.  I don't know if just changing the match will actually fix things in that way.

**Comment by frapontillo** [comment]
For my specific use case the change would solve it, since all other sourceMap references are wrongly put there, probably by `awesome-typescript-loader` in my `webpack` flow.

**Comment by frapontillo** [comment]
The issue was fixed in the originating repository, so this isn't needed anymore: https://github.com/s-panferov/awesome-typescript-loader/issues/60. Thanks!
