### ISSUE TITLE
Gulp: No such file or directory

### ISSUE THREAD

**Issue by ghpabs** [SitePen/remap-istanbul#25]
I'm running `remap-instanbul` via Gulp with the configuration below:

**Gulp tasks**
```js
gulp.task('remap-istanbul', function () {
    return gulp.src('coverage/json/coverage-js.json')
        .pipe(remapIstanbul({
            reports: {
                json: 'coverage/json/coverage-ts.json',
                html: 'coverage/html-report'
            }
        }));
});
```

This is how I transpile my TypeScript to JavaScript. Note that I move the transpiled code to `/build` folder.

```js
gulp.task('ts', function() {
	var tsResult = gulp.src('src/**/*.ts')
		.pipe(plugins.sourcemaps.init())
		.pipe(plugins.typescript(tsProject));

	return tsResult
		.js
		.pipe(plugins.sourcemaps.write())
		.pipe(gulp.dest('build/js'));
});
```

For some reason the plugin changes my working directory to **`C:\source`** which isn't correct. The correct directory structure should be something like: `C:\myproject\src\app\main.ts`.

**Console**

```
[15:20:24] Starting 'remap-istanbul'...
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\source\app\main.ts'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at LookupStore.Store.mix.get (C:\agent-ui\SCP_WD_MCA_UI_Seed\node_modules\remap-istanbul\node_modules\istanbul\lib\store\fslookup.js:40:19)
```

Am I missing something?

**Comment by kitsonk** [comment]
I think this is related to #11

**Comment by ghpabs** [comment]
Okay I'll subscribe to issue #11. Let me know if you need more info about my setup.

Thanks for sharing this project.

**Comment by ghpabs** [comment]
**Update** 

I fixed it by adding `sourceRoot` when transpiling the TypeScript.

```
function ts() {
	var tsResult = gulp.src('src/**/*.ts')
		.pipe(plugins.sourcemaps.init())
		.pipe(plugins.typescript(tsProject));

	return tsResult
		.js
		.pipe(plugins.sourcemaps.write('./', {
			sourceRoot: __dirname + '/src'
		}))
		.pipe(gulp.dest('build/js'));
}
```
