### ISSUE TITLE
Failing with 'Line must be greater than or equal to 1, got '

### ISSUE THREAD

**Issue by riggerthegeek** [SitePen/remap-istanbul#39]
My project is failing to remap a particular file.  It's a file that's extending the `Error` class - when I don't extend the Error class, it remaps fine.

I suspect that this isn't a remap-istanbul error, but would appreciate any suggestions as to why it may be failing. I've spent most of today looking at this

Thanks

The full error is...

```bash
/Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/node_modules/source-map/lib/source-map-consumer.js:538
        throw new TypeError('Line must be greater than or equal to 1, got '
        ^

TypeError: Line must be greater than or equal to 1, got 0
    at SourceMapConsumer_findMapping [as _findMapping] (/Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/node_modules/source-map/lib/source-map-consumer.js:538:15)
    at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/node_modules/source-map/lib/source-map-consumer.js:603:24)
    at getMapping (/Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/lib/remap.js:64:25)
    at /Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/lib/remap.js:213:20
    at Array.forEach (native)
    at /Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/lib/remap.js:211:37
    at Array.forEach (native)
    at /Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/lib/remap.js:173:22
    at Array.forEach (native)
    at remap (/Users/semms/Documents/Development/Cromwell/cromwell-api-services/node_modules/remap-istanbul/lib/remap.js:172:12)
```

The class it's trying to remap is...

```javascript
'use strict';

class IOCException extends Error {
    constructor(message) {
        super();

        this.name = 'IOCException';
        this.message = message;

        Error.captureStackTrace(this, this.constructor.name);
    }
}

export default IOCException;
```

The JSON that's failing to remap
```json
{"path":"/Users/semms/Documents/Development/Cromwell/cromwell-api-services/__build__/src/node_modules/lib/ioc/IOCException.js","s":{"1":1,"2":0,"3":0,"4":1,"5":1,"6":0,"7":0,"8":1,"9":0,"10":0,"11":0,"12":1,"13":1,"14":0,"15":1,"16":1,"17":1,"18":1,"19":1,"20":1,"21":0,"22":0,"23":1,"24":1,"25":1},"b":{"1":[1,0],"2":[1,1],"3":[0,0],"4":[0,0,0],"5":[0,0],"6":[0,0],"7":[0,0],"8":[0,0,0],"9":[0,0],"10":[0,1],"11":[1,0],"12":[0,0],"13":[1,1],"14":[1,0],"15":[1,0]},"f":{"1":0,"2":0,"3":0,"4":0,"5":1,"6":1,"7":0},"fnMap":{"1":{"name":"(anonymous_1)","skip":true,"loc":{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},"line":3},"2":{"name":"(anonymous_2)","skip":true,"loc":{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},"line":3},"3":{"name":"_classCallCheck","loc":{"start":{"line":7,"column":0},"end":{"line":7,"column":48}},"line":9},"4":{"name":"_possibleConstructorReturn","loc":{"start":{"line":9,"column":0},"end":{"line":9,"column":48}},"line":15},"5":{"name":"_inherits","loc":{"start":{"line":11,"column":0},"end":{"line":11,"column":41}},"line":21},"6":{"name":"(anonymous_6)","loc":{"start":{"line":13,"column":19},"end":{"line":13,"column":37}},"line":27},"7":{"name":"IOCException","loc":{"start":{"line":16,"column":4},"end":{"line":16,"column":28}},"line":30}},"statementMap":{"1":{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},"2":{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},"3":{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},"4":{"start":{"line":3,"column":0},"end":{"line":3,"column":0}},"5":{"start":{"line":7,"column":0},"end":{"line":7,"column":0}},"6":{"start":{"line":7,"column":50},"end":{"line":7,"column":50}},"7":{"start":{"line":7,"column":92},"end":{"line":7,"column":90}},"8":{"start":{"line":9,"column":0},"end":{"line":9,"column":0}},"9":{"start":{"line":9,"column":50},"end":{"line":9,"column":50}},"10":{"start":{"line":9,"column":63},"end":{"line":9,"column":61}},"11":{"start":{"line":9,"column":50},"end":{"line":9,"column":48}},"12":{"start":{"line":11,"column":0},"end":{"line":11,"column":0}},"13":{"start":{"line":11,"column":43},"end":{"line":11,"column":43}},"14":{"start":{"line":11,"column":106},"end":{"line":11,"column":104}},"15":{"start":{"line":11,"column":43},"end":{"line":11,"column":41}},"16":{"start":{"line":11,"column":41},"end":{"line":11,"column":374}},"17":{"start":{"line":11,"column":390},"end":{"line":11,"column":374}},"18":{"start":{"line":13,"column":0},"end":{"line":13,"column":4}},"19":{"start":{"line":14,"column":4},"end":{"line":13,"column":37}},"20":{"start":{"line":16,"column":4},"end":{"line":16,"column":4}},"21":{"start":{"line":17,"column":8},"end":{"line":16,"column":28}},"22":{"start":{"line":19,"column":8},"end":{"line":16,"column":28}},"23":{"start":{"line":22,"column":4},"end":{"line":13,"column":37}},"24":{"start":{"line":33,"column":0},"end":{"line":33,"column":0}},"25":{"start":{"line":34,"column":0},"end":{"line":34,"column":0}}},"branchMap":{"1":{"line":3,"type":"cond-expr","locations":[{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true}]},"2":{"line":3,"type":"binary-expr","locations":[{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true}]},"3":{"line":3,"type":"cond-expr","locations":[{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true}]},"4":{"line":3,"type":"binary-expr","locations":[{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true},{"start":{"line":0,"column":0},"end":{"line":0,"column":0},"skip":true}]},"5":{"line":10,"type":"if","locations":[{"start":{"line":7,"column":50},"end":{"line":7,"column":50}},{"start":{"line":7,"column":50},"end":{"line":7,"column":50}}]},"6":{"line":16,"type":"if","locations":[{"start":{"line":9,"column":50},"end":{"line":9,"column":50}},{"start":{"line":9,"column":50},"end":{"line":9,"column":50}}]},"7":{"line":18,"type":"cond-expr","locations":[{"start":{"line":9,"column":226},"end":{"line":9,"column":159}},{"start":{"line":9,"column":233},"end":{"line":9,"column":159}}]},"8":{"line":18,"type":"binary-expr","locations":[{"start":{"line":9,"column":159},"end":{"line":9,"column":159}},{"start":{"line":9,"column":168},"end":{"line":9,"column":168}},{"start":{"line":9,"column":196},"end":{"line":9,"column":196}}]},"9":{"line":18,"type":"cond-expr","locations":[{"start":{"line":9,"column":175},"end":{"line":9,"column":175}},{"start":{"line":9,"column":175},"end":{"line":9,"column":175}}]},"10":{"line":22,"type":"if","locations":[{"start":{"line":11,"column":43},"end":{"line":11,"column":43}},{"start":{"line":11,"column":43},"end":{"line":11,"column":43}}]},"11":{"line":22,"type":"binary-expr","locations":[{"start":{"line":11,"column":47},"end":{"line":11,"column":47}},{"start":{"line":11,"column":83},"end":{"line":11,"column":83}}]},"12":{"line":23,"type":"cond-expr","locations":[{"start":{"line":11,"column":194},"end":{"line":11,"column":194}},{"start":{"line":11,"column":194},"end":{"line":11,"column":194}}]},"13":{"line":24,"type":"binary-expr","locations":[{"start":{"line":11,"column":244},"end":{"line":11,"column":244}},{"start":{"line":11,"column":258},"end":{"line":11,"column":258}}]},"14":{"line":24,"type":"if","locations":[{"start":{"line":11,"column":41},"end":{"line":11,"column":41}},{"start":{"line":11,"column":41},"end":{"line":11,"column":41}}]},"15":{"line":24,"type":"cond-expr","locations":[{"start":{"line":11,"column":414},"end":{"line":11,"column":390}},{"start":{"line":11,"column":460},"end":{"line":11,"column":460}}]}},"l":{"0":1,"3":1,"7":1,"9":1,"11":1,"13":1,"14":1,"16":1,"17":0,"19":0,"22":1,"33":1,"34":1}}
```

**Comment by riggerthegeek** [comment]
NB. Although the example given is using the Gulp example in the Wiki, I get the same error when I use the CLI version too.

**Comment by kitsonk** [comment]
Sorry for the delayed response, but it seems to indicate that the source map is somehow invalid.  You have provided the coverage, but do you happen to have the source map for the above example?  It could be that whatever transpiler is doing is outputting some invalid destinations.

You could use a tool like [Source Map Visualization](https://sokra.github.io/source-map-visualization/) to see what is mapped where.

Right now, we don't swallow errors like that, but I guess we could, though you would have no idea that we were dropping out coverage.

**Comment by riggerthegeek** [comment]
In truth, I can't remember. It's certainly plausible that it was a source map error.

I'm no longer working on that project so it's not something I can add to. I'll mark it as closed and hopefully it was a problem on my end rather than yours (the amount I used your project elsewhere without issue makes me think it probably is the case)
