### ISSUE TITLE
Error: Unable to find entry for [...]

### ISSUE THREAD

**Issue by alexgorbatchev** [SitePen/remap-istanbul#45]
I'm trying to use the gulp plugin and it doesn't seem to work.

```js
gulp.task('test:remap-istanbul', function() {
  var remapIstanbul = require('remap-istanbul/lib/gulpRemapIstanbul');
  return gulp.src('coverage/coverage.json')
    .pipe(remapIstanbul({
      reports: {
        'html': 'coverage/--html-report',
      }
    }));
});
```

Throws this error:

```
gulp test:remap-istanbul
[11:32:05] Requiring external module ts-node/register
[11:32:07] Using gulpfile ~/1/hot-reload-example/gulpfile.ts
[11:32:07] Starting 'test:remap-istanbul'...

/.../node_modules/remap-istanbul/node_modules/istanbul/lib/store/memory.js:38
            throw new Error('Unable to find entry for [' + key + ']');
                  ^
Error: Unable to find entry for [src/components/BannerComponent-spec.tsx]
    at MemoryStore.Store.mix.get (/.../node_modules/remap-istanbul/node_modules/istanbul/lib/store/memory.js:38:19)
    at HtmlReport.Report.mix.writeDetailPage (/.../node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:411:67)
    at /.../node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/.../node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/.../node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /.../node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/.../node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:482:23)
    at /.../node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (native)
```

However, from command line with everything else being the same, it works wonderfully:

```
$ ./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/html-report -t html
```

What am I doing wrong?

**Comment by kitsonk** [comment]
I think this had a fair amount to do with the issues encountered when using sources contained in a source map.  Could you try `0.6.3` and see if the issue persists?

**Comment by EarthCitizen** [comment]
I am seeing the same issue in 0.6.4 via karma-remap-istanbul 0.2.1

**Comment by knightbk** [comment]
I am having the same error when running the same thing. 

    ./node_modules/.bin/remap-istanbul -i coverage/coverage-final.json -o coverage/html-report -t html
    C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\store\memory.js:38
                throw new Error('Unable to find entry for [' + key + ']');
                ^

    Error: Unable to find entry for [app\app.component.ts]
        at MemoryStore.Store.mix.get (C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\store\memory.js:38:19)
        at HtmlReport.Report.mix.writeDetailPage (C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\report\html.js:411:67)
        at C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\report\html.js:489:26
        at SyncFileWriter.extend.writeFile (C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\util\file-writer.js:57:9)
        at FileWriter.extend.writeFile (C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\util\file-writer.js:147:23)
        at C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\report\html.js:488:24
        at Array.forEach (native)
        at HtmlReport.Report.mix.writeFiles (C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\report\html.js:482:23)
        at C:\Users\bknight\Source\Repos\pf\pf.Presentation.Angular2\node_modules\istanbul\lib\report\html.js:484:22
        at Array.forEach (native)

**Comment by bertofer** [comment]
Having this error as well
```
12 09 2016 10:10:00.495:ERROR [karma]: [Error: Unable to find entry for [src/app/app.component.ts]]
Error: Unable to find entry for [src/app/app.component.ts]
    at MemoryStore.Store.mix.get (/Users/alberto/Projects/personal/angular2-electron/node_modules/istanbul/lib/store/memory.js:38:19)
    at HtmlReport.Report.mix.writeDetailPage (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:411:67)
    at /Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:489:26
    at SyncFileWriter.extend.writeFile (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:482:23)
    at /Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:482:23)
    at HtmlReport.Report.mix.writeReport (/Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/node_modules/istanbul/lib/report/html.js:566:14)
    at /Users/alberto/Projects/personal/angular2-electron/node_modules/remap-istanbul/lib/writeReport.js:77:22
    at /Users/alberto/Projects/personal/angular2-electron/node_modules/amdefine/amdefine.js:125:34
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by EarthCitizen** [comment]
@bertofer As a work-around, you can disable the HTML reporting for karma-remap-istanbul and just execute remap-istanbul after Karma runs. This is what several people have done while this issue remains unresolved.

**Comment by Elecash** [comment]
I can confirm that this is not happening in v0.5.1 to me.

I hope that this leads you to the problem :)

**Comment by majanord** [comment]
I'm getting this error:
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unable to find entry for ....
or something similar when using version 0.7.0 -> 0.9.5 while it there's no error from 0.5.1 - 0.6.4 thx for the idea for the temporary fix @Elecash .

**Comment by pgarge** [comment]
Version 0.9.5 was working with Angular 4 and html report was generated.

If I upgrade to Angular 5 and keep all the other packages same I get the same error.

If I comment the html reporting line there is no error.

Versions lower than 0.7.0 don't work with Angular 5 either.
