### ISSUE TITLE
Searches for many, non-existant source maps; doesn't use existing source map

### ISSUE THREAD

**Issue by Victorystick** [SitePen/remap-istanbul#47]
1. I bundle the tests for an app using Rollup, yielding a single bundle (`dist/app-tests.js`) and source map `dist/app-tests.js.map`) with all source contents inlined.

1. I run `istanbul cover _mocha -- dist/app-tests.js` yielding a `coverage/coverage.json` file.

1. The coverage file is remapped successfully to `coverage/coverage-remapped.json` with a basePath set to the directory of the bundled code. All file paths are relative to the coverage file.

1. *But*, when I try to generate a report:

```
remap-istanbul -i coverage/coverage-remapped.json -o html-report -t html
```

remap-istanbul outputs a long list of warnings

```
[Error: Could not find source map for: "../node_modules/lodash-es/noop.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isObject.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isFunction.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/toNumber.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/toInteger.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/rest.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/spread.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/eq.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isLength.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isArrayLike.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isObjectLike.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isArrayLikeObject.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isArguments.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/isArray.js"]
[Error: Could not find source map for: "../node_modules/lodash-es/assign.js"]
[Error: Could not find source map for: "../src/a.js"]
[Error: Could not find source map for: "../src/b.js"]
...
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '../main.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    ...
```

Any thoughts as to why remap-istanbul is searching for all these source map files instead of the `dist/app-tests.js.map` that _actually_ exists? Is it somehow related to #33?

**Comment by kitsonk** [comment]
Remapping an already remapped coverage file is an unsupported use case.  If you want to generate a report, you should back to the original unmapped coverage file:

```
remap-istanbul -i coverage/coverage.json -o html-report -t html
```

You can of course just supply the `coverage-remapped.json` directly to Istanbul too to write out the reports.
