### ISSUE TITLE
HTML Report issue on Windows.

### ISSUE THREAD

**Issue by snovak7** [SitePen/remap-istanbul#66]
Well, I was trying to remap a report but I am getting this weird report error with html

```console
events.js:141
      throw er; // Unhandled 'error' event
      ^
 TypeError: Cannot read property 'split' of null
    at HtmlReport.Report.mix.writeDetailPage (K:\platform\node_modules\istanbul\lib\report\html.js:412:30)
    at K:\platform\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (K:\platform\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (K:\platform\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at K:\platform\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (K:\platform\node_modules\istanbul\lib\report\html.js:482:23)
    at K:\platform\node_modules\istanbul\lib\report\html.js:484:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (K:\platform\node_modules\istanbul\lib\report\html.js:482:23)
```

but when I tried to text...

```console
--------------------|----------|----------|----------|----------|----------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------|----------|----------|----------|----------|----------------|
 /source/main/core\ |       12 |        0 |        0 |       12 |                |
  application.ts    |       12 |        0 |        0 |       12 |... 127,134,135 |
 /source/main\      |    66.67 |       50 |       25 |    66.67 |                |
  bootstrap.ts      |       60 |      100 |       25 |       60 |    63,64,72,79 |
  index.ts          |       80 |       50 |      100 |       80 |             32 |
--------------------|----------|----------|----------|----------|----------------|
All files           |     32.5 |       25 |     9.09 |     32.5 |                |
--------------------|----------|----------|----------|----------|----------------|
```

This also made directories in weird places (K:\source\main\**), and lastly incomplete in project (K:\platform\coverage\reports\html), with config below:

```typescript
  @Task("test/remap", ["test/analyze"])
  testReMap() {
    return gulp
      .src("./coverage/reports/json/coverage.json")
      .pipe(remapIstanbul({
        fail: true,
        reports: {
          'html': './coverage/reports/html',
          'text': null,
        }
      }));
  }
```

Also a note, an excerpt from coverage.json looks like this:

```json
{
  "K:\\platform\\coverage\\src\\main\\index.js": {
    "path": "K:\\platform\\coverage\\src\\main\\index.js",
    "s": {}
  }
}
```

Versions:
"gulp-istanbul": "^0.10.4",
"remap-istanbul": "^0.6.4"

**Comment by snovak7** [comment]
Tried also on my Mac, same problem with HTML report exception, but a bit different with text output
But it doesn't output the assuming by exception (writeDetailPage ) detail page...

**Comment by snovak7** [comment]
I found the solution to my problem... because my environment is separating source of typescript with javascript

i had to set basePath, which is of "typescript" files:
```typescript
  @Task("test/remap", ["test/analyze"])
  testReMap() {
    return gulp
      .src("./coverage/reports/json/coverage.json")
      .pipe(remapIstanbul({
        fail: true,
        // basePath: "path/to/*.ts", // This
        reports: {
          'html': './coverage/reports/html',
          'text': null,
        }
      }));
  }
```

and also sourceRoot was wrong in sourcemaps which was default: "/source/", out of unknown reason, which I changed in configuration with:

```node
.pipe(sourcemaps.write('.', {includeContent: false, sourceRoot: ''}))
```

Now works both on Mac and Windows.
