### ISSUE TITLE
Test suite failures in Windows

### ISSUE THREAD

**Issue by gertsonderby** [SitePen/remap-istanbul#84]
Running the tests in Windows results in a plethora of failures. I used PowerShell to run the command given inside the test runner script (which, being a bash script does not work at all, of course), and got 16/60 failures for the latter reported test group.

I suspect a lot of these failures may be due to inconsistency in path handling, which does not take into consideration that Windows paths are separated with backslash. I'm trying to figure out a fix to that one as a knock-on from trying to solve that problem within the [SystemJS Istanbul hook](https://github.com/guybedford/systemjs-istanbul). A PR will come if and when I have an idea how to sort it.

**Comment by gitgrimbo** [comment]
Windows and Git Bash @ 6608623, 17/60 failed for me:

````
Total: [××✓✓✓✓✓✓✓✓✓✓✓✓✓××✓✓××××✓✓✓×××××✓×✓✓✓✓✓✓✓] 60/60
Passed: 43  Failed: 17  Skipped: 0
````

**Comment by gertsonderby** [comment]
I ended up digging into this a bit further, and the problem stems from the use of the node.js path functions to manipulate URLs. My above references PR was a bad solution, and did not solve the underlying problem. Switching all usage of `path` to `path.posix` would probably fix things.

**Comment by gitgrimbo** [comment]
Ah ok.  I had pulled in your branch and it fixed a lot of the tests (for me), but there were still some failures.  Such as (I force the `opts.verbose` option on the html reporter to see where it's saving files):

````
Write asset: d:\dev\git_repos\remap-istanbul\tmp\html-report-main\base.css
Write asset: d:\dev\git_repos\remap-istanbul\tmp\html-report-main\sort-arrow-sprite.png
Write asset: d:\dev\git_repos\remap-istanbul\tmp\html-report-main\sorter.js
Write asset: d:\dev\git_repos\remap-istanbul\tmp\html-report-main\prettify.css
Write asset: d:\dev\git_repos\remap-istanbul\tmp\html-report-main\prettify.js
Writing d:\dev\git_repos\remap-istanbul\tmp\html-report-main\index.html
Writing d:\dev\git_repos\remap-istanbul\tmp\html-report-main\tests\unit\support\index.html
Writing d:\dev\git_repos\remap-istanbul\tmp\html-report-main\tests\unit\support\inlinesource.ts.html
tmp\html-report-main\support\inlinesource.ts.html
false
FAIL: main - inline sources (4998ms)
AssertionError: expected false to be true
  at Assertion.<anonymous>  <node_modules\intern\browser_modules\chai\chai.js:567:10>
  at Assertion.addProperty  <node_modules\intern\browser_modules\chai\chai.js:4240:29>
  at Function.6.module.exports.assert.isTrue  <node_modules\intern\browser_modules\chai\chai.js:2483:31>
  at <tests\unit\main.js:47:12>
  at process._tickCallback  <internal\process\next_tick.js:103:7>
1/3 tests failed (2 skipped)
````

Seems the report gets written to an unexpected folder:

- Expected `tmp\html-report-main\support\inlinesource.ts.html`
- Actual `tmp\html-report-main\tests\unit\support\inlinesource.ts.html`
